[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/youtube-card/api/:splat"
  status = 200
  force = true

[[edge_functions]]
  function = "rate-limit"
  path = "/api/*"
